# This is a basic workflow to help you get started with Actions

name: IP Workflow

# Controls when the workflow will run
on:
  schedule:
    - cron: "30 3 * * *"
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CF_KV_API: https://api.cloudflare.com/client/v4/accounts/${{secrets.CF_ACCOUNT_ID}}/storage/kv/namespaces/${{secrets.CF_NAMESPACE_ID}}/values
  PING_API: https://api.globalping.io/v1/measurements
  PING_LIMIT: 3
  PROXYS: proxys
  PROXYS_BAK: proxys_bak
  PROXYS_UPDATED: proxys_updated
  PROXYS_JSON: proxys.json
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-ip:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.put-data.outputs.data }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
      - name: download ip zip file, unzip, merge, uniq
        run: |
          curl -o ip.zip https://zip.baipiao.eu.org
          unzip ip.zip -d ip
          cat ip/*.txt | sort | uniq > ip.txt
          echo zip `wc -l ip.txt` | tee $GITHUB_STEP_SUMMARY
          
      - name: backup original data, merge
        run: |
          for key in $PROXYS_BAK $PROXYS; do
            ret=`curl -H "Authorization:Bearer ${{secrets.CF_API_TOKEN}}" "$CF_KV_API/$key"`
            if echo "$ret"|grep error; then
              echo $ret
            elif [ ! -z "$ret" ] && ! echo "$ret"|grep '443":[]' ]; then
              echo "$ret" |tr -d '{"[]}'|sed -r 's/, ?/\n/g'|sed -r '/^\w*:$/d'|sed -r 's/^\w*:([\d\.]*)/\1/' >> ip.txt
              if [ $key == $PROXYS ]; then
                curl -X PUT -H "Authorization:Bearer ${{secrets.CF_API_TOKEN}}" -d "$ret" "$CF_KV_API/$PROXYS_BAK"
              fi
            fi
          done
          echo `cat $PROXYS_JSON`|tr -d '["]'|sed -r 's/, ?/\n/g' >> ip.txt
          cat ip.txt | sort | uniq > tmp.txt
          mv tmp.txt ip.txt
          echo merge `wc -l ip.txt` | tee $GITHUB_STEP_SUMMARY
  
      - name: http test, filter
        run: |
          UA="Mozilla/5.0 Chrome/107.0.0.0 Safari/537.36"
          measure_ping(){
            [ -z $1 ] && echo 'error: no ip' && exit 1
            local ip=$1
            local url=`curl -H "content-type: application/json" -A "$UA" \
              -d '{"type":"ping","target":"'$ip'","locations":[{"country":"HK","limit":2}]}' \
              -si "$PING_API"|grep location|awk '{print $2}'|tr -d '\n\r'`
            sleep 1
            while true; do
              local r=`curl -A "$UA" -s "$url"`
              case "$r" in
                *in-progress*)
                  sleep 1; continue ;;
                *loss\":0*)
                  local avg=`echo $r|sed -n 's/.*avg":\(\w*\).*/\1/p'`
                  ([ "$avg" = "null" ] || [ $avg -ge 200 ]) && return 1
                  echo $ip $url $avg; return 0 ;;
                *)
                  return 1 ;;
              esac
            done
          }
          # ip port
          measure_http(){
            [ -z $1 ] && echo 'error: no ip' && exit 1
            local ip=$1 port=$2 protocol=http
            [ -z "$port" ] && port=443
            [ $port -eq 443 ] && protocol=https
            local url=`curl -H "content-type: application/json" -A "$UA" \
              -d '{"type":"http","target":"'$ip'","locations":[{"country":"HK","limit":'$PING_LIMIT'}],"measurementOptions":{"port":"'$port'","protocol":"'$protocol'"}}' \
              -si "$PING_API"|grep location|awk '{print $2}'|tr -d '\n\r'`
            sleep 1
            while true; do
              local r=`curl -A "$UA" -s "$url"` n=$PING_LIMIT avg=0
              case "$r" in
                *in-progress*)
                  sleep 1; continue ;;
                *authorized\":*)
                  #measure_ping $ip && echo "$ip" >> ip$port.txt; 
                  #local d=`echo $r|tr -s '{,.}' '\n'|grep expiresAt|grep -v null|tr -s '"T' ' '|awk '{printf "%s %s\n",$3,$4}'|head -n 1`
                  #[ -z "$d" ] || [ $((`date -d "$d" +%s`-`date +%s`)) -lt 86400 ] && break
                  
                  #eval `echo $r|sed -n 's/.*total":\(\w*\),.*total":\(\w*\),.*/local a=\1 b=\2/p'`;
                  local nulln=`echo $r|tr -s '{,}' '\n'|grep total|grep null|wc -l`
                  [ $nulln -gt 1 ] && break;
                  n=$(($n-$nulln))
                  local m=`echo $r|tr -s '{,}' '\n'|grep total|grep -v null|cut -d ':' -f2`
                  for t in $m; do avg=$(($avg+$t)); done
                  avg=$(($avg/$n))
                  echo $ip:$port $url $avg;
                  [ $avg -gt 0 ] && [ $avg -lt 500 ] && echo "$ip" >> ip$port.txt;
                  break ;;
                *cloudflare*)
                  [ $port -eq 80 ] && echo $ip:$port $url; echo "$ip" >> ip$port.txt; 
                  break ;;
                *)
                  break ;;
              esac
            done
          }
          measure_openai(){
            [ -z $1 ] && echo 'error: no ip' && exit 1
            local ip=$1 port=443
            local url=`curl -H "content-type: application/json" -A "$UA" \
              -d '{"type":"http","target":"'$ip'","locations":[{"country":"HK","limit":'$PING_LIMIT'}],"measurementOptions":{"port":'$port',"protocol":"https","request":{"method":"GET","host":"android.chat.openai.com","path":"/public-api/mobile/server_status/v1"}}}' \
              -si "$PING_API"|grep location|awk '{print $2}'|tr -d '\n\r'`
            [ -z $url ] && echo 'error: no url' && exit 1
            sleep 1
            while true; do
              local r=`curl -A "$UA" -s "$url"` n=$PING_LIMIT avg=0
              local m=`echo $r|tr -s '{,}' '\n'|grep total|cut -d ':' -f2`
              for t in $m; do 
                [ $t = null ] && n=$(($n-1)) || avg=$(($avg+$t)); 
              done
              [ $n -gt 0 ] && avg=$(($avg/$n))
              case "$r" in
                *in-progress*)
                  sleep 1; continue ;;
                *status\\\":\\\"normal*statusCode\":200*)
                  echo $ip:$port $url $avg normal;
                  echo "$ip" >> ipopenai.txt;
                  #echo "$ip" >> ip$port.txt;
                  break;;
                *disallowed\ ISP*)
                  echo $ip:$port $url $avg disallowed ISP;
                  [ $avg -gt 0 ] && [ $avg -lt 1000 ] && echo "$ip" >> ip$port.txt;
                  break;;
                *unsupported_country*)
                  echo $ip:$port $url $avg unsupported_country;
                  [ $avg -gt 0 ] && [ $avg -lt 1000 ] && echo "$ip" >> ip$port.txt;
                  break;;
                *)
                  echo $ip:$port $url $avg;
                  break;;
              esac
            done
          }
          
          while IFS= read -r ip; do
            measure_openai $ip
          done < ip.txt
          while IFS= read -r ip; do
            measure_http $ip 80
          done < ip443.txt
          [ -s ipopenai.txt ] && while IFS= read -r ip; do
            measure_http $ip 80
          done < ipopenai.txt
          echo `wc -l ip443.txt`| tee $GITHUB_STEP_SUMMARY
          echo `wc -l ip80.txt` | tee $GITHUB_STEP_SUMMARY
          echo `wc -l ipopenai.txt`| tee $GITHUB_STEP_SUMMARY
          
      - id: put-data
        name: update valid ip to server
        run: |
          data=
          for i in 443 80 openai; do
            if [ -s ip$i.txt ]; then
              [ ! -z $data ] && data=$data,
              data=$data'"'$i'":'[$(echo `sed -r 's/^(.*)$/"\1"/' ip$i.txt`|tr -s ' ' ',')]
            fi
          done
          data={$data}
          curl -X PUT -H "Authorization:Bearer ${{secrets.CF_API_TOKEN}}" \
            -d "$data" "$CF_KV_API/$PROXYS" >> $GITHUB_STEP_SUMMARY
          curl -X PUT -H "Authorization:Bearer ${{secrets.CF_API_TOKEN}}" \
            -d "`date +%s`" "$CF_KV_API/$PROXYS_UPDATED"
          echo "data=$data" >> $GITHUB_OUTPUT
          
      # - name: upload ip file
        # uses: actions/upload-artifact@v4
        # with:
          # name: cfproxys
          # path: |
            # ip443.txt
            # ip80.txt
            
  deploy:
    needs: update-ip
    uses: ./.github/workflows/update_host.yml
    with:
      proxys: ${{ needs.update-ip.outputs.data }}
    secrets: inherit