# This is a basic workflow to help you get started with Actions

name: cfhost Workflow

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 * * * *"
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  #  branches: [ "main" ]
  #  paths-ignore: 
  #    - '.gitignore'
  #    - 'package-lock.json'
  #  - 'dist/**'
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deployPage:
        description: 'deploy worker and page (default only worker)'
        required: false
        default: false
        type: boolean

env:
  deployPage: ${{inputs.deployPage}}
  CF_KV_API: https://api.cloudflare.com/client/v4/accounts/${{secrets.CF_ACCOUNT_ID}}/storage/kv/namespaces/${{secrets.CF_NAMESPACE_ID}}/values
  CF_SCRIPT_API: https://api.cloudflare.com/client/v4/accounts/${{secrets.CF_ACCOUNT_ID}}/workers/scripts
  CF_PROJECT_API: https://api.cloudflare.com/client/v4/accounts/${{secrets.CF_ACCOUNT_ID}}/pages/projects
  CFHOST: cfhost
  CFHOST_BAK: cfhost_bak
  CFHOSTJSON: cfhost.json
  SCRIPT: v2
  PROJECT: v1
  ENTRY: _worker.js

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with: 
          # https://github.com/orgs/community/discussions/25797#discussioncomment-3249294
          fetch-depth: 0
          
      - id: s1
        name: get cfhost, merge, backup
        run: |
          merge_backup(){
            local ret=`curl -H "Authorization:Bearer ${{secrets.CF_API_TOKEN}}" "$CF_KV_API/$1"`
            if echo "$ret"|grep error; then
              echo $ret;
            elif [ ! -z "$ret" ] && [ ! "$ret" = "[]" ]; then
              echo $ret|tr -d '[]'|sed -r 's/, ?/\n/g' > tmp.txt
              local bak=`curl -H "Authorization:Bearer ${{secrets.CF_API_TOKEN}}" "$CF_KV_API/$2"`
              if ! echo "$bak"|grep error && [ ! -z "$bak" ] && [ ! "$bak" = "[]" ]; then
                echo $bak|tr -d '[]'|sed -r 's/, ?/\n/g' >> tmp.txt
                ret=[$(echo `cat tmp.txt|sort -u`|tr -s ' ' ',')]
              fi
              echo `cat $3`|tr -d '[]'|sed -r 's/, ?/\n/g' >> tmp.txt
              echo [$(echo `cat tmp.txt|sort -u`|tr -s ' ' ',')] > $3
              curl -X PUT -H "Authorization:Bearer ${{secrets.CF_API_TOKEN}}" \
                -d "$ret" "$CF_KV_API/$2" >> $GITHUB_STEP_SUMMARY
            fi
          }
          echo "s1 merge backup" >> $GITHUB_STEP_SUMMARY
          merge_backup $CFHOST $CFHOST_BAK $CFHOSTJSON
          
      - id: s2
        name: check change of cfhost.json, worker code
        env:
          GH_TOKEN: ${{ github.token }}
        run: |          
          if ! git diff|grep "$CFHOSTJSON"; then
            # git config user.name "GitHub Actions Bot"
            # git config user.email "<>"
            # git add $CFHOSTJSON
            # git commit -m "updated cfhost"
            # git push
            echo "s2 check change" >> $GITHUB_STEP_SUMMARY
            echo "cfhost not update" >> $GITHUB_STEP_SUMMARY
            # if trigger workflow manually then skip
            [ ! -z ${{ github.event.before }} ] && [ ! -z ${{ github.event.after }} ] || exit 0;
            if [ -z `git diff --name-only ${{ github.event.before }} ${{ github.event.after }} 2>&1` ]; then
              echo "code nothing update" >> $GITHUB_STEP_SUMMARY
              gh run cancel ${{ github.run_id }}
              gh run watch ${{ github.run_id }}
            fi
          fi
          
      - id: s3
        if: steps.s2.conclusion == 'success'
        name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: build worker
        run: |
          npm i
          npm run esbuild
          
      # - name: upload dist
        # uses: actions/upload-artifact@v4
        # with:
          # name: cf-worker
          # path: dist
          
      - name: deploy worker, page
        run: |
          [ ! -s "dist/$ENTRY" ] && echo "$ENTRY not found!" && exit;
          echo "s5 deploy worker.." >> $GITHUB_STEP_SUMMARY
          curl -X PUT -H "Authorization:Bearer ${{secrets.CF_API_TOKEN}}" \
            -H 'Content-Type: multipart/form-data' \
            --form "worker.js=@dist/$ENTRY;type=application/javascript+module" \
            --form 'metadata={"main_module":"'$ENTRY'"}' \
            --url $CF_SCRIPT_API/$SCRIPT/content | tail -n 4 >> $GITHUB_STEP_SUMMARY
          [ ! $deployPage ] && exit;
          echo "deploy page.." >> $GITHUB_STEP_SUMMARY
          curl -X POST -H "Authorization:Bearer ${{secrets.CF_API_TOKEN}}" \
            -H 'Content-Type: multipart/form-data' \
            --form "$ENTRY=@dist/$ENTRY;type=application/javascript" \
            --form 'manifest={}' \
            --form 'branch=test' \
            --url $CF_PROJECT_API/$PROJECT/deployments | tail -n 4 >> $GITHUB_STEP_SUMMARY